/*

 SMILERSPRITES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Smiler[] =
{
  0x10,0x10,0x1C,0x1C,0x20,0x00,0xAC,0x00,
  0x3C,0x00,0xF2,0xF2,0x7E,0x7E,0x00,0x00,
  0x10,0x00,0x1C,0x00,0x20,0x20,0xAC,0xAC,
  0x3C,0x3C,0xF2,0x00,0x7E,0x00,0x00,0x00
};

/* End of SMILERSPRITES.C */
